name: m1-mathinfo
# channels priority
# conda-forge has highest priority
channels:
  - defaults
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  # Python environment
  - python>=3.9
  - pip
  # Pari/GP
  - pari
  # interactive widgets in notebooks
  - ipywidgets>=7.6,<8
  # Jupyter archive to decompress archive files
  # https://github.com/jupyterlab-contrib/jupyter-archive
  # - jupyter-archive
  - pip:
    # Print module version
    - watermark
    # Pari-gp in jupyter
    - pari-jupyter
    # JupyterLab Variable inspector
    # https://github.com/lckr/jupyterlab-variableInspector
    # - lckr-jupyterlab-variableinspector
